### PR TITLE
Update bloom.go

### PR DESCRIPTION
**Pull request by moredure**

### CODE REVIEW

**Comment by lemire** [comment]
I welcome additional tests but I don’t think that they are in the right file.

**Comment by lemire** [comment]
Ok. Let us wait for the tests.

**Comment by moredure** [comment]
Should we run go fmt for entire codebase?

**Comment by lemire** [comment]
Yes, do an `fmt` please.

**Comment by moredure** [comment]
Looks like the fmt issue originate from original codebase and my code doesn't have the parts needed to be go fmt'ed

**Comment by lemire** [comment]
Thanks.

**Pull request merged**
